DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
SET search_path TO public;

CREATE TABLE QUser (
    sid BIGSERIAL PRIMARY KEY,
    username VARCHAR(128) NOT NULL UNIQUE,
    password VARCHAR(128) NOT NULL,
    name VARCHAR(128) NOT NULL,
    email VARCHAR(128) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT 'true',
    createdOn TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    lastLogin TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE QTree (
    sid BIGSERIAL PRIMARY KEY,
    name VARCHAR(128) NOT NULL UNIQUE,
    description VARCHAR(512) DEFAULT NULL,
    createdOn TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    modifiedOn TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    CreatedBy BIGINT NOT NULL,
    FOREIGN KEY (CreatedBy) REFERENCES QUser (sid) ON DELETE CASCADE
);

CREATE TABLE QStructureType (
    sid BIGSERIAL PRIMARY KEY,
    name VARCHAR(128) NOT NULL UNIQUE,
    description VARCHAR(512) DEFAULT NULL,
    glycoName VARCHAR(128) NOT NULL UNIQUE,
    createdOn TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    modifiedOn TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    CreatedBy BIGINT NOT NULL,
    InTree BIGINT NOT NULL,
    FOREIGN KEY (CreatedBy) REFERENCES QUser (sid) ON DELETE CASCADE,
    FOREIGN KEY (InTree) REFERENCES QTree (sid) ON DELETE CASCADE
);

CREATE TABLE QStructure (
    sid BIGSERIAL PRIMARY KEY,
    filename VARCHAR(128) NOT NULL,
    hash VARCHAR(128) NOT NULL UNIQUE,
    spec TEXT NOT NULL,
    contents TEXT NOT NULL,
    status VARCHAR(8) NOT NULL,
    version VARCHAR(32) DEFAULT NULL,
    uri VARCHAR(256) DEFAULT NULL UNIQUE,
    createdOn TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    modifiedOn TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    HasType BIGINT NOT NULL,
    CreatedBy BIGINT NOT NULL,
    CHECK (status in ('pending', 'reviewed', 'deferred', 'approved', 'rejected')),
    FOREIGN KEY (HasType) REFERENCES QStructureType (sid) ON DELETE CASCADE,
    FOREIGN KEY (CreatedBy) REFERENCES QUser (sid) ON DELETE CASCADE
);

CREATE TABLE QProvenance (
    sid BIGSERIAL PRIMARY KEY,
    action VARCHAR(10) NOT NULL,
    uri VARCHAR(256) DEFAULT NULL UNIQUE,
    createdOn TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    modifiedOn TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    CreatedBy BIGINT NOT NULL,
    HasProvenance BIGINT NOT NULL,
    CHECK (action in ('toPending', 'toReviewed', 'toDeferred', 'toApproved', 'toRejected', 'toOntology')),
    FOREIGN KEY (CreatedBy) REFERENCES QUser (sid) ON DELETE CASCADE,
    FOREIGN KEY (HasProvenance) REFERENCES QStructure (sid) ON DELETE CASCADE
);

CREATE TABLE QSource (
    sid BIGSERIAL PRIMARY KEY,
    name VARCHAR(128) NOT NULL UNIQUE,
    uri VARCHAR(256) NOT NULL UNIQUE,
    createdOn TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    modifiedOn TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    CreatedBy BIGINT NOT NULL,
    FOREIGN KEY (CreatedBy) REFERENCES QUser (sid) ON DELETE CASCADE
);

CREATE TABLE QAnnotation (
    sid BIGSERIAL PRIMARY KEY,
    comment VARCHAR(512) NOT NULL,
    uri VARCHAR(256) DEFAULT NULL UNIQUE,
    createdOn TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    modifiedOn TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    HasAnnotation BIGINT NOT NULL,
    CreatedBy BIGINT NOT NULL,
    FOREIGN KEY (HasAnnotation) REFERENCES QStructure (sid) ON DELETE CASCADE,
    FOREIGN KEY (CreatedBy) REFERENCES QUser (sid) ON DELETE CASCADE
);

CREATE TABLE QReference (
    sid BIGSERIAL PRIMARY KEY,
    srcId VARCHAR(128) NOT NULL,
    uri VARCHAR(256) DEFAULT NULL UNIQUE,
    createdOn TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    modifiedOn TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    HasReference BIGINT NOT NULL,
    CreatedBy BIGINT NOT NULL,
    HasSource BIGINT NOT NULL,
    FOREIGN KEY (HasReference) REFERENCES QStructure (sid) ON DELETE CASCADE,
    FOREIGN KEY (CreatedBy) REFERENCES QUser (sid) ON DELETE CASCADE,
    FOREIGN KEY (HasSource) REFERENCES QSource (sid) ON DELETE CASCADE
);

CREATE TABLE QRole (
    sid BIGSERIAL PRIMARY KEY,
    name VARCHAR(128) NOT NULL UNIQUE,
    createdOn TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    modifiedOn TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    CreatedBy BIGINT NOT NULL,
    FOREIGN KEY (CreatedBy) REFERENCES QUser (sid) ON DELETE CASCADE
);

CREATE TABLE QUserHasRoleQRole (
    account BIGINT NOT NULL,
    role BIGINT NOT NULL,
    UNIQUE(account,role),
    FOREIGN KEY (account) REFERENCES QUser (sid) ON DELETE CASCADE,
    FOREIGN KEY (role) REFERENCES QRole (sid) ON DELETE CASCADE
);

CREATE TABLE QUserTracksQStructure (
    tracker BIGINT NOT NULL,
    tracked BIGINT NOT NULL,
    UNIQUE(tracker,tracked),
    FOREIGN KEY (tracker) REFERENCES QUser (sid) ON DELETE CASCADE,
    FOREIGN KEY (tracked) REFERENCES QStructure (sid) ON DELETE CASCADE
);